---
- name: Manage NTP on app servers
  hosts: app
  become: true
  tasks:

    - name: Install NTP package
      ansible.builtin.apt:
        name: "{{ ntp_package }}"
        state: present
        update_cache: true

    - name: Ensure NTP service is started and enabled
      ansible.builtin.service:
        name: "{{ ntp_service }}"
        state: started
        enabled: true

- name: Install utility package on db servers
  hosts: db
  become: true
  tasks:

    - name: Install curl package
      ansible.builtin.apt:
        name: "{{ utility_package }}"
        state: present
        update_cache: true